#ifndef RACESIMULATOR_ERROR_HANDLER_H
#define RACESIMULATOR_ERROR_HANDLER_H

#define ERROR_FILE_OPENING "ERROR: COULDN'T OPEN FILE WITH PATH %s!"
#define ERROR_MEMORY_ALLOCATION "ERROR: COULDN'T PERFORM MEMORY ALLOCATION FOR %s!"
#define ERROR_AT_LINE "ERROR WHILE PARSING LINE %d OF FILE %s!"
#define ERROR_MIN_VALUE_VIOLATED "FIELD %s MUST BE HIGHER THAN %d!"
#define ERROR_INT_CONVERSION "FIELD %s COULDN'T BE CONVERTED TO INT"
#define ERROR_STRTOK "COULDN'T TOKENIZE FIELD %s!"
#define ERROR_BUFFER_SIZE_EXCEEDED "BUFFER MAX SIZE (%d) EXCEEDED!"
#define ERROR_INSUFFICIENT_NUM_LINES "ERROR: INSUFFICIENT NUMBER OF LINES AT FILE %s! IT MUST BE %d!"
#define ERROR_FLOAT_SIZE_EXCEEDED "FIELD %s EXCEEDS FLOAT MAX SIZE!"
#define ERROR_FLOAT_CONVERSION "FIELD %s COULDN'T BE CONVERTED TO FLOAT!"
#define ERROR_SHM_CREATION "ERROR: COULDN'T CREATE SHARED MEMORY!"
#define ERROR_MEMORY_ATTACHMENT "ERROR: COULDN'T ATTACH MEMORY TO %d!"
#define ERROR_SEM_CREATION "ERROR: COULDN'T CREATE %s SEMAPHORE!"
#define ERROR_UNLINK_SEM "ERROR: COUNDN'T UNLINK % NAMED SEMAPHORE!"
#define ERROR_MEMORY_DETACHMENT "ERROR: COULDN'T DETACH MEMORY OF %d!"
#define ERROR_MEMORY_RM "ERROR: COULDN'T REMOVE MEMORY ASSOCIATED WITH ID %d!"
#define ERROR_SEM_CLOSE "ERROR: COULDN'T CLOSE %s SEMAPHORE!"

#define MAX_ERROR_MSG_SIZE 100

void throw_error(int exit_program, const char * error_msg, ...);
void reset(void);
void exit_later(void);

#endif //RACESIMULATOR_ERROR_HANDLER_H
