//
// Created by Sancho on 01/04/2021.
//

#ifndef RACESIMULATOR_ERROR_HANDLER_H
#define RACESIMULATOR_ERROR_HANDLER_H

#define ERROR_FILE_OPENING "ERROR: COULDN'T OPEN FILE WITH PATH %s!"
#define ERROR_MEMORY_ALLOCATION "ERROR: COULDN'T PERFORM MEMORY ALLOCATION FOR %s!"
#define ERROR_AT_LINE "ERROR WHILE PARSING LINE %d OF FILE %s!"
#define ERROR_MIN_VALUE_VIOLATED "%s MUST BE HIGHER THAN %d!"
#define ERROR_INT_CONVERSION "FIELD %s COULDN'T BE CONVERTED TO INT"
#define ERROR_STRTOK "COULDN'T TOKENIZE FIELD %s!"
#define ERROR_BUFFER_SIZE_EXCEEDED "BUFFER MAX SIZE (%d) EXCEEDED!"
#define ERROR_INSUFFICIENT_NUM_LINES "ERROR: INSUFFICIENT NUMBER OF LINES AT FILE %s! IT MUST BE %d!"
#define ERROR_FLOAT_SIZE_EXCEEDED "FIELD %s EXCEEDS FLOAT MAX SIZE!"
#define ERROR_FLOAT_CONVERSION "FIELD %s COULDN'T BE CONVERTED TO FLOAT!"

void throw_error(const char * error_msg, ...);

#endif //RACESIMULATOR_ERROR_HANDLER_H
