#ifndef RACESIMULATOR_DEBUG_H
#define RACESIMULATOR_DEBUG_H

#define SHM_CREATED "SHARED MEMORY CREATED WITH ID %d!"
#define SHM_ATTACHED "SHARED MEMORY WITH ID %d ATTACHED TO CURRENT PROCESS ADDRESSING ZONE!"
#define SEM_CREATED "SEMAPHORE WITH NAME %s CREATED!"

#define SHM_DETACHED "DETACHED SHARED MEMORY WITH ID %d!"
#define SHM_REMOVED "REMOVED SHARED MEMORY WITH ID %d!"
#define SEM_CLOSED "CLOSED SEMAPHORE WITH NAME %s!"
#define SEM_UNLINKED "UNLINK SEMAPHORE WITH NAME %s!"

#define RACE_CONFIG_CREATED "CREATED RACE CONFIGURATION!"

void debug_msg(const char * file, int line, const char * msg, ...);

#endif //RACESIMULATOR_DEBUG_H
