#ifndef RACESIMULATOR_ERROR_HANDLER_H
#define RACESIMULATOR_ERROR_HANDLER_H

#define ERROR_FILE_OPENING "ERROR: COULDN'T OPEN FILE WITH PATH %s!"
#define ERROR_FILE_WRITE "ERROR: COULDN'T WRITE ON FILE WITH PATH %s!"
#define ERROR_FILE_CLOSING "ERROR: COULDN'T CLOSE FILE WITH PATH %s!"

#define ERROR_MEMORY_ALLOCATION "ERROR: COULDN'T PERFORM MEMORY ALLOCATION FOR %s!"

#define ERROR_AT_LINE "ERROR WHILE PARSING LINE %d OF FILE %s!"
#define ERROR_INSUFFICIENT_NUM_LINES "ERROR: INSUFFICIENT NUMBER OF LINES AT FILE %s! IT MUST BE %d!"
#define ERROR_MIN_VALUE_VIOLATED "FIELD %s MUST BE HIGHER OR EQUAL THAN %.2f!"
#define ERROR_MAX_VALUE_VIOLATED "FIELD %s MUST BE LOWER OR EQUAL THAN %.2f!"
#define ERROR_STRTOK "COULDN'T TOKENIZE FIELD %s!"
#define ERROR_BUFFER_SIZE_EXCEEDED "BUFFER MAX SIZE (%d) EXCEEDED!"
#define ERROR_INT_CONVERSION "FIELD %s COULDN'T BE CONVERTED TO INT"
#define ERROR_FLOAT_SIZE_EXCEEDED "FIELD %s EXCEEDS FLOAT MAX SIZE!"
#define ERROR_FLOAT_CONVERSION "FIELD %s COULDN'T BE CONVERTED TO FLOAT!"
#define ERROR_INVALID_TIME_INTERVAL "%s VALUE MUST BE SUPERIOR TO %s VALUE"

#define ERROR_SHM_CREATION "ERROR: COULDN'T CREATE SHARED MEMORY!"
#define ERROR_MEMORY_ATTACHMENT "ERROR: COULDN'T ATTACH MEMORY WITH ID %d!"
#define ERROR_MEMORY_DETACHMENT "ERROR: COULDN'T DETACH MEMORY WITH ID %d!"
#define ERROR_MEMORY_RM "ERROR: COULDN'T REMOVE MEMORY WITH ID %d!"
#define ERROR_SEM_CREATION "ERROR: COULDN'T CREATE %s SEMAPHORE!"
#define ERROR_SEM_CLOSE "ERROR: COULDN'T CLOSE %s SEMAPHORE!"
#define ERROR_UNLINK_SEM "ERROR: COULDN'T UNLINK % NAMED SEMAPHORE!"

#define ERROR_NOT_IMPLEMENTED "ERROR: %s FUNCTIONALITY IS NOT IMPLEMENTED!"

#define ERROR_CREATE_PROCESS "ERROR: COULDN'T CREATE PROCESS %s!"
#define ERROR_CREATE_THREAD "ERROR: COULDN'T CREATE THREAD %s!"


#define ERROR_GENERATE_LOG_ENTRY "ERROR: COULDN'T GENERATE %s LOG ENTRY!"

#define MAX_ERROR_MSG_SIZE 100

#define throw_error_end_exit(error_msg, ...) throw_error(true, error_msg, __VA_ARGS__)
#define throw_error_end_stay(error_msg, ...) throw_error(false, error_msg, __VA_ARGS__)

void throw_error(int exit_process, const char * error_msg, ...);

#endif //RACESIMULATOR_ERROR_HANDLER_H
