#ifndef RACESIMULATOR_EXCEPTION_HANDLER_H
#define RACESIMULATOR_EXCEPTION_HANDLER_H

#include <semaphore.h>

#define FILE_OPENING_EXCEPTION "FILE_OPENING_EXCEPTION: COULDN'T OPEN FILE WITH PATH %s!"
#define FILE_WRITING_EXCEPTION "FILE_WRITING_EXCEPTION: COULDN'T WRITE ON FILE WITH PATH %s!"
#define FILE_CLOSING_EXCEPTION "FILE_CLOSING_EXCEPTION: COULDN'T CLOSE FILE WITH PATH %s!"

#define MEMORY_ALLOCATION_EXCEPTION "MEMORY_ALLOCATION_EXCEPTION: COULDN'T PERFORM MEMORY ALLOCATION FOR %s!"

#define ERROR_AT_LINE "ERROR WHILE PARSING LINE %d OF FILE %s!"
#define INSUFFICIENT_NUM_LINES_EXCEPTION "INSUFFICIENT_NUM_LINES_EXCEPTION: INSUFFICIENT NUMBER OF LINES AT FILE %s! IT MUST BE %d!"
#define MIN_VALUE_EXCEPTION "MIN_VALUE_EXCEPTION: FIELD %s MUST BE HIGHER OR EQUAL THAN %.2f!"
#define MAX_VALUE_EXCEPTION "MAX_VALUE_EXCEPTION: FIELD %s MUST BE LOWER OR EQUAL THAN %.2f!"
#define TOKENIZING_EXCEPTION "TOKENIZING_EXCEPTION: COULDN'T TOKENIZE FIELD %s!"
#define BUFFER_SIZE_EXCEEDED_EXCEPTION "BUFFER_SIZE_EXCEEDED_EXCEPTION: BUFFER MAX SIZE (%d) EXCEEDED!"
#define INT_CONVERSION_EXCEPTION "INT_CONVERSION_EXCEPTION: FIELD %s COULDN'T BE CONVERTED TO INT"
#define FLOAT_SIZE_EXCEEDED_EXCEPTION "FLOAT_SIZE_EXCEEDED_EXCEPTION: FIELD %s EXCEEDS FLOAT MAX SIZE!"
#define FLOAT_CONVERSION_EXCEPTION "FLOAT_CONVERSION_EXCEPTION: FIELD %s COULDN'T BE CONVERTED TO FLOAT!"

#define SHM_CREATION_EXCEPTION "SHM_CREATION_EXCEPTION: COULDN'T CREATE SHARED MEMORY!"
#define MEMORY_ATTACHMENT_EXCEPTION "MEMORY_ATTACHMENT_EXCEPTION: COULDN'T ATTACH MEMORY WITH ID %d!"
#define MEMORY_DETACHMENT_EXCEPTION "MEMORY_DETACHMENT_EXCEPTION: COULDN'T DETACH MEMORY WITH ID %d!"
#define MEMORY_REMOVAL_EXCEPTION "MEMORY_REMOVAL_EXCEPTION: COULDN'T REMOVE MEMORY WITH ID %d!"
#define SEM_CREATION_EXCEPTION "SEM_CREATION_EXCEPTION: COULDN'T CREATE SEMAPHORE NAMED %s!"
#define SEM_CLOSE_EXCEPTION "SEM_CLOSE_EXCEPTION: COULDN'T CLOSE SEMAPHORE NAMED %s!"
#define SEM_UNLINK_EXCEPTION "SEM_UNLINK_EXCEPTION: COULDN'T UNLINK SEMAPHORE NAMED %s!"
#define SEM_WAIT_EXCEPTION "WAIT_SEM_EXCEPTION: COULDN'T PERFORM WAIT OPERATION ON SEMAPHORE NAMED %s!"
#define SEM_POST_EXCEPTION "WAIT_SEM_EXCEPTION: COULDN'T PERFORM POST OPERATION ON SEMAPHORE NAMED %s!"

#define NOT_IMPLEMENTED_EXCEPTION "NOT_IMPLEMENTED_EXCEPTION: %s FUNCTIONALITY IS NOT IMPLEMENTED!"

#define CREATION_PROCESS_EXCEPTION "CREATION_PROCESS_EXCEPTION: COULDN'T CREATE PROCESS %s!"
#define CREATION_THREAD_EXCEPTION "CREATION_THREAD_EXCEPTION: COULDN'T CREATE THREAD %s!"

#define LOG_ENTRY_GENERATION_EXCEPTION "LOG_ENTRY_GENERATION_EXCEPTION: COULDN'T GENERATE %s LOG ENTRY!"
#define LOG_MODE_NOT_SUPPORTED_EXCEPTION "LOG_MODE_NOT_SUPPORTED_EXCEPTION: %s LOG MODE NOT SUPPORTED!"

#define MAX_EXCEPTION_MSG_SIZE 100

#define throw_exception_and_exit(exception_msg, ...) throw_exception(__FILE__, __LINE__, true, exception_msg, __VA_ARGS__)
#define throw_exception_and_stay(exception_msg, ...) throw_exception(__FILE__, __LINE__, false, exception_msg, __VA_ARGS__)

extern sem_t * exc_mutex;
extern void (* clean_func)(void *);
extern void * clean_func_params;

void exc_handler_init(sem_t * sem, void (* clean_function)(void *), void * clean_function_params);
void throw_exception(const char * file_name, int line, int exit_process, const char * exception_msg, ...);


#endif //RACESIMULATOR_EXCEPTION_HANDLER_H