#ifndef STATS_HELPER_STATS_HELPER_H
#define STATS_HELPER_STATS_HELPER_H

#define RACE_STATISTICS "RACE STATISTICS"
#define CAR_ID "ID"
#define CAR_TEAM_ID "TEAM ID"
#define CAR_NAME "CAR"
#define CAR_TEAM_NAME "TEAM NAME"
#define CAR_STATE "STATE"
#define CAR_NUM_COMPLETED_LAPS "LAPS"
#define CAR_NUM_BOX_STOPS "BOX STOPS"
#define RACE_NUM_MALFUNCTIONS "MALFUNCTIONS: "
#define RACE_NUM_REFUELS "REFUELS: "
#define RACE_NUM_CARS_ON_TRACK "CARS ON TRACK: "

#define BUFFER_SIZE 2048
#define NUM_TOP_CARS 5
#define MAX_DIGITS 4
#define NUM_COLS 7
#define MAX_STATE_LENGTH 5
#define HORIZONTAL_DELIM "-"

#endif //STATS_HELPER_STATS_HELPER_H